### ISSUE TITLE
require is not defined in Linkify.js

### ISSUE THREAD

**Issue by djpandit007** [tasti/react-linkify#43] opened 2017-07-26 21:10 UTC
Uncaught ReferenceError: require is not defined
    at eval (Linkify.js:10)
    at Object.<anonymous> (application.js?e57a035…:10974)
    at __webpack_require__ (vendor.js?e57a035…:74)
    at eval (Description.js:4)
    at Object.<anonymous> (application.js?e57a035…:8226)
    at __webpack_require__ (vendor.js?e57a035…:74)
    at eval (Header.js:33)
    at Object.<anonymous> (application.js?e57a035…:8232)
    at __webpack_require__ (vendor.js?e57a035…:74)
    at eval (View.js:15)

**Comment by pablolmiranda** [comment] 2017-07-31 17:48
Could you please provide an example project on a github repo that reproduces the issue?

**Comment by tasti** [comment] 2018-01-07 00:25
Closing due to staleness.

**Closed by tasti** 2018-01-07 00:25 UTC
